name: Pull request

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, ci_setup ]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload test report
        uses: actions/upload-artifact@v4.3.0
        with:
          name: lint_report
          path: app/build/reports/lint-results-debug.html

  unit-tests:
    name: Run Unit tests
    needs: [ lint ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Unit tests
        run: bash ./gradlew test

      - name: Upload report
        uses: actions/upload-artifact@v4.3.0
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/


